### PR TITLE
Add support for multisite clustering

### PR DESCRIPTION
**Pull request by rarsan**
This enables multi-AZ deployments improving HA/DR & allowing for data locality.
More details in Splunk docs:
http://docs.splunk.com/Documentation/Splunk/latest/Indexer/Multisitearchitecture

### CODE REVIEW

**Comment by rarsan** [comment]
Hey folks, what can we do to push this along?

**Comment by pburkholder** [comment]
For those interested, see also https://github.com/BestBuy/splunk_cookbook/pull/29# for discussion of these features and the status of splunk cookbooks for the community.

**Comment by rarsan** [comment]
Hey @tas50, @jtimberman : did you get the chance to take a look at this?

**Comment by jtimberman** [comment]
@rarsan Sorry, I don't have cycles to review this as I'm not working on this cookbook at this time.

**Comment by rarsan** [comment]
No worries, @jtimberman . We've been adding most commonly requested features such as multisite clustering, to license master linkup, and custom datastore dir:
https://github.com/rarsan/chef-splunk/releases/tag/v1.4.0-rarsan.4
Perhaps some of us can offer a hand to work on this repo or become peer reviewer to avoid/minimize divergence?

**Pull request merged**
