### PR TITLE
enable amazon platform support for splunk forwarder install

### PR DESCRIPTION
**Pull request by cbrichard**
### Description

This change adds support for the amazon linux family allowing the install of splunk-forwarder on 
the Amazon Linux AMI.  Added test kitchen file for testing against Amazon EC2.

Signed-off-by: Christopher Richard <christopher.richard27@gmail.com>

Mentioning as co-contributor
@tfitch

### CODE REVIEW

**Comment by tas50** [comment]
@cbrichard You'll need to sign off the individual commits in this PR before we can accept it. Also instead of using a kitchen ec2 config you can use either the amazonlinux docker container in dokken or the amazon linux virtualbox image for the standard test kitchen config. 

Check it out at https://github.com/chef-cookbooks/activemq/blog/master/.kitchen.yml

**Comment by cbrichard** [comment]
@tas50 I made this commit from my work laptop this time.  Just FYI, you will see the email address is different.  

I wanted to comment as an FYI I have been working with @tfitch (Tyler Fitch) on this contribution and when running the tests we noticed that the server specific test were failing.  We filter out those checks during the kitchen test and verified that that all the client test passed which my change only adds support for the chef-splunk forwarder client install and nothing dealing with the server.

Please let me know if this will suffice or if you need more detail or testing before merging.

**Comment by andrewelizondo** [comment]
Is there anything preventing this from being merged @tas50?

**Comment by tas50** [comment]
Nope. Sorry for the delay. I'll get this released

**Pull request merged**
