### PR TITLE
Enable Splunk installs from OS repo

### PR DESCRIPTION
**Pull request by Sauraus**
Fixes: https://github.com/chef-cookbooks/chef-splunk/issues/50

### CODE REVIEW

**Comment by jtimberman** [comment]
This has a merge conflict due to the change introduced in 68601d2. However, I don't know if I'm a fan of the additional complexity this will bring. This cookbook already has a lot of attributes, and this adds more to the attribute sprawl.

**Comment by Sauraus** [comment]
What alternative to the attribute do you suggest?

**Comment by jtimberman** [comment]
I don't know that it needs an alternative? I imagine the reason to do this is to mainly allow for installation on a network that doesn't have direct access to download from Splunk. We already have URL attributes that can be set to download from an internal package instead.

**Comment by Sauraus** [comment]
@jtimberman it's had actually to do with having a controlled source from where you install, not all IT, especially security department allow the installation of packages from outside the corporate firewall of reviews etc.

Leveraging the native OS install method of a package repo is probably a better option than just having a URL from which to download.

**Comment by tas50** [comment]
@Sauraus If you're still interested in this PR can you rebase it so I can merge it?

**Comment by haidangwa** [comment]
This will need to be reworked now that `splunk_installer` is a real resourec and no longer a definition

**Comment by haidangwa** [comment]
This could be resolved without adding another node attribute. I think the cookbook could approach this by defaulting to the OS package managers if the URL attribute is empty. So, anyone using this can simply set `node['splunk']['forwarder']['url'] = ''` and `node['splunk']['server']['url'] = ''` if they didn't want to use a download from an external URL.

There would need to be some added logic in `splunk_installer` where if the URL is empty then skip the `remote_file` execution and the package installer resource does not specify anything for `source`. The latter would force chef to install the package from OS package manager, which would need to be handled by whomever is responsible for their server.

**Comment by haidangwa** [comment]
Closing this in favor of PR #124

**Pull request closed without merging**
