### PR TITLE
Refactor inputs.conf rendering to support multiple types

### PR DESCRIPTION
**Pull request by Sauraus**
Fixes: https://github.com/chef-cookbooks/chef-splunk/issues/36

### CODE REVIEW

**Comment by ryanl-ee** [comment]
Hi Sauraus, would you mind taking a look at this Travis failure? I used file monitors as well and would love for this to become merged into master. Thanks!

**Comment by Sauraus** [comment]
I will do so yes

**Comment by danieljimenez** [comment]
+1

**Comment by Sauraus** [comment]
Ok this is weird, I cannot repro the failure::

```
chef-splunk::client
  creates the local system directory
  creates an outputs template in the local system directory
  notifies the splunk service to restart when rendering the outputs template
  inputs config has hosts
    creates an inputs template in the local system directory if it has hosts
    notifies the splunk service to restart when rendering the inputs template

Finished in 1 minute 0.33 seconds (files took 2.9 seconds to load)
53 examples, 0 failures
```

**Comment by haidangwa** [comment]
Looks like this was addressed in #105. If you think there are additional features missing, please open a new issue.

**Pull request closed without merging**
