### PR TITLE
Add support for changing listening port.

### PR DESCRIPTION
**Pull request by danieljimenez**
In our environment, an application server listens on port 8089 so I've added the ability to change the port via an attribute.

### CODE REVIEW

**Comment by jtimberman** [comment]
This needs a spec similar to [setup_ssl_spec.rb](https://github.com/chef-cookbooks/chef-splunk/blob/master/spec/recipes/setup_ssl_spec.rb#L31-L37). 

The web.conf file is also managed in the [setup_ssl recipe](https://github.com/chef-cookbooks/chef-splunk/blob/master/recipes/setup_ssl.rb#L43-L47).  This should either move to a recipe that both client and setup_ssl include, or this resource be modified to match the resource in `setup_ssl` and the README.md updated to note that the recipes must not be on the same run list, since they both manage the file.

Further, it could be modified such that the same template is used for both recipes.

**Comment by danieljimenez** [comment]
Thanks @jtimberman, which would you suggest? I want to make the cookbook as compatible as possible for all users.

**Comment by jtimberman** [comment]
Given that we have a separate recipe for the service resource, I think that a recipe included by both `client` and `setup_ssl` is probably the best, most flexible option.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @danieljimenez

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by rarsan** [comment]
Splunk .conf files are generally not as cohesive as recipes. For example, web.conf spans different areas from SSL, to ports, custom endpoints, etc. Therefore, I've often encountered such template 'conflict' between recipes. One way I've worked around this is to use the CLI, thereby avoid depending on common template entirely. For example, for the case above, you can have:
```ruby
execute 'update-splunk-mgmt-port' do
  command "#{splunk_cmd} set splunkd-port #{node['splunk']['mgmt_port']} -auth '#{splunk_auth_info}'"
  not_if "#{splunk_cmd} show splunkd-port -auth '#{splunk_auth_info}' | grep ': #{node['splunk']['mgmt_port']}'"
  notifies :restart, 'service[splunk]'
end
```

It has its own pros & cons:
It's particularly powerful when doing complex configuration where a single command replaces many .conf lines, and avoids the need to manage a template. This is especially the case if you're used to configuring via Splunk CLI.
However, for small changes (like this one), it's arguably less readable & flexible than templates.

@jtimberman, what do you think? I like your suggestion of having recipes include a common recipe, say `setup_web` as it allows us to use either approach. How would `setup_ssl` pass forward the ssl_options to `setup_web` in that case?

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by haidangwa** [comment]
@tas50 I think this PR should be closed. The suggestion made by @rarsan was merged into master with commit a72d348db46b056253f23143a292c52cbd7a4224

**Pull request closed without merging**
